config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'products#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :products, only: [:show] do
    resources :bookings, only: [:new, :create]
    resources :favorites, only: [:create]
  end

  resources :bookings, only: [:index, :destroy]
  resources :favorites, only: [:index, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :product

  validates :start_date, presence: true
  validates :end_date, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :bookings
  has_many :users, through: :bookings

  validates :name, presence: true
  validates :description, presence: true
  validates :city, presence: true
  validates :price, presence: true

  include PgSearch::Model
  pg_search_scope :global_search,
    against: {
      name: 'A',
      description: 'B',
      city: 'C'
    },
    using: {
      tsearch: { prefix: true }
    }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :bookings
  has_many :favorites
  has_many :products, through: :bookings
  has_many :fav_products, through: :favorites, class_name: "Product", foreign_key: "product_id", source: :product
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = current_user.bookings
  end

  def new
    @booking = Booking.new(user_id: current_user)
    @product = Product.find(params[:product_id])
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.product = Product.find(params[:product_id])
    @booking.user = current_user
    if @booking.save
      redirect_to bookings_path
    else
      render :new
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to bookings_path
  end

  private

  def booking_params
    params.require(:booking).permit(:price, :start_date, :end_date)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def index
    @favorites = Favorite.all
  end

  def create
    @favorite = Favorite.new
    @favorite.user = current_user
    @product = Product.find(params[:product_id])
    @favorite.product = @product
    @favorite.save
    redirect_to root_path(anchor: @product.id)
  end

  def destroy
    @favorite = Favorite.find(params[:id])
    @favorite.destroy
    redirect_to favorites_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    if params[:query].present?
      @products = Product.global_search(params[:query])
    else
      @products = Product.all
    end
  end

  def show
    @product = Product.find(params[:id])
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div class="container pt-5 pb-5">
  <h1>Your bookings</h1>
  <div class="row d-flex mt-4">
      <% @bookings.each do |booking| %>
        <div class="booking-cards bg-white mb-4">
            <div class="booking-card d-flex">
              <%= image_tag booking.product.photo, class: "product-image col-sm-12 col-lg-8 p-4" %>
              <div class="product-show-content col-sm-12 col-lg-4 d-flex align-items-end flex-column mt-2">
                <div class="product-content-text">
                  <div class="product-description">
                    <h1><%= booking.product.name %></h1>
                    <br>
                    <p><%= booking.product.description %></p>
                    <br>
                    <p><%= booking.product.city %></p>
                  </div>
                  <br>
                  <div class="booking-dates">
                    <p>From <%= booking.start_date %> to <%= booking.end_date %></p>
                  </div>
                  <br>
                  <div class="booking-price">
                    <% booking.duration = (booking.end_date - booking.start_date).to_i %>
                    <% booking.price = booking.product.price * booking.duration %>
                    <div id="booking-price-day"><%= booking.product.price %> €/day for <%= booking.duration %> days</div>
                    <div id="booking-total-price">Total: <%= booking.price %> €</div>
                  </div>
                </div>
                <div class="booking-container-btn mt-auto">
                  <div class="booking-btn">
                    <%= link_to 'Cancel booking', booking_path(booking), method: :delete, class: 'btn', style: "width: 100%; font-weight: bold; color: white" %>
                  </div>
                </div>
              </div>
            </div>
        </div>
      <% end %>
  </div>
</div>

app/views/bookings/new.html.erb
<div class="container d-flex align-items-center pt-5 pb-5">
  <div class="form-wrapper" style="width: 400px; margin: 0 auto;">
    <h2>Select your rental dates</h2>

    <%= simple_form_for ([@product, @booking]) do |f| %>
      <%= f.input :start_date, as: :string, required: false, input_html: {class: "datepicker"} %>
      <%= f.input :end_date, as: :string, required: false, input_html: {class: "datepicker"} %>
      <br>
      <%= f.button :submit, "Book it!", class: "btn" %>
    <% end %>
  </div>
</div>

app/views/favorites/index.html.erb
<div class="container pt-5 pb-5">
  <h1>Your favorites</h1>
  <div class="card-container d-flex flex-wrap">
    <% @favorites.each do |favorite| %>
      <div class="card">
        <div class="imgBox">
          <%= image_tag favorite.product.photo %>
        </div>
        <div class="details">
          <div class="textContent">
            <h3><%= favorite.product.name %></h3>
            <h2 class="price"><%= favorite.product.price %> €/day</h2>
          </div>
          <p><%= link_to 'See product', product_path(favorite.product), class: 'btn' %></p>
          <p><%= link_to 'Remove', favorite_path(favorite), method: :delete, class: 'btn mt-1' %></p>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RentACrib</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>

    <%= render'shared/footer' %>
  </body>

</html>

app/views/products/index.html.erb
<div class="banner">
  <div class="search-feature">
    <%= form_tag root_path, method: :get, class: 'd-flex' do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control search-bar d-flex",
        placeholder: "Search by name or city"
      %>
        <%= submit_tag "Search", class: "btn btn-info search-button m-0" %>
    <% end %>
  </div>
</div>

<div class="container pb-4">
  <div class="row d-flex justify-content-center mx-3 mt-3">
    <%= link_to 'See all products', root_path, class: 'btn btn-info' %>
  </div>
  <div class="card-container pt-2 d-flex justify-content-center flex-wrap">
    <% @products.each do |product| %>
      <div class="card" id="<%= product.id %>">
        <% if current_user && current_user.fav_products.include?(product) %>
          <i class="fas fa-heart fav-prod fav-prod-color-red"></i>
        <% else %>
          <%= link_to product_favorites_path(product), method: :post, remote: :true do  %>
            <i class="fas fa-heart fav-prod"></i>
          <% end %>
        <% end %>
          <p class="city-name-card"><%= product.city %></p>
        <div class="imgBox">
          <%= image_tag product.photo %>
        </div>
        <div class="details">
          <div class="textContent">
            <h3><%= product.name %></h3>
            <h2 class="price"><%= product.price %> €/day</h2>
          </div>
          <p><%= link_to 'See more', product_path(product), class: 'btn' %></p>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/products/show.html.erb
<div class="container pt-5 pb-5">
  <div class="row d-flex">
    <%= image_tag @product.photo, class: "product-image col-sm-12 col-lg-8" %>
    <div class="product-show-content col-sm-12 col-lg-4">
      <div class="product-content-text d-flex align-items-end flex-column">
        <div class="product-price">
          <p><%= @product.price %> € per day</p>
        </div>
        <div class="product-description">
          <h1><%= @product.name %></h1><br>
          <p><%= @product.description %></p><br>
          <p><%= @product.city %></p>

        </div>
        <div class="product-btn-container">
          <div class='product-btn'>
            <%= link_to 'Book it!', new_product_booking_path(@product), class: 'btn btn-info mb-3', style: "width: 100%; font-weight: bold; color: white" %>
          </div>
          <div class="product-btn">
            <%= button_to 'Send a message to owner', '#', class: 'btn btn-light mb-3', style: "width: 100%; font-weight: bold; color: white", id: "disabledbutton" %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="mt-4">
    <%= link_to '< Back', root_path, id: 'back-btn', class: 'btn' %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer d-flex">
  <div class="footer-links">
    <a href="https://github.com/srouchon/RENT_A_CRIB"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This prototype website is made with <i class="fas fa-heart"></i> by Sophie, Vic, Deva and Ophélie.
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "logo_projet.png" %>
    <% end %>

  <div class="title-logo-navbar navbar-nav mr-auto flex-column">
    <div class="title-logo">RENT A CRIB</div>
    <div class="title-slogan">GIVE A NEW LIFE TO CHILD CARE</div>
  </div>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item-active">
          <%= link_to "Favorites", favorites_path, class: "nav-link" %>
        </li>
        <li class="nav-item">

        </li>
        <li class="nav-item dropdown">
          <%= image_tag "sophie.jpg", class: "avatar dropdown-toggle rounded-circle", gravity: :face, id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "My Bookings", bookings_path, class: "dropdown-item" %>
            <%= link_to "Settings", edit_user_registration_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>